### ISSUE TITLE
[docs] live block generation is broken for some old versions

### ISSUE THREAD

**Issue by charlieegan3** [open-policy-agent/opa#5593]
When working on https://github.com/open-policy-agent/opa/pull/5592 I was unable to run `make netlify-prod`. All tasks complete other than `make live-blocks-inject` which fails with a large error starting with:

```

--- Errors for ../../public//docs/v0.36.1/policy-performance/index.html ---
ChainedError: indexed evaluation failed for an unexpected, possibly internal reason (check for additional logs): unable to perform local evaluation
    at /Users/charlieegan3/Code/opa/docs/website/scripts/live-blocks/src/preprocess/index.js:217:13
    at async process (/Users/charlieegan3/Code/opa/docs/website/scripts/live-blocks/src/helpers.js:171:18)
    at async Promise.all (index 0)
    at async batchProcess (/Users/charlieegan3/Code/opa/docs/website/scripts/live-blocks/src/helpers.js:177:3)
    at async populateOutputs (/Users/charlieegan3/Code/opa/docs/website/scripts/live-blocks/src/preprocess/index.js:196:3)
    at async processFile (/Users/charlieegan3/Code/opa/docs/website/scripts/live-blocks/src/preprocess/index.js:72:3)
    at async handleLater (/Users/charlieegan3/Code/opa/docs/website/scripts/live-blocks/src/helpers.js:151:13)
    at async /Users/charlieegan3/Code/opa/docs/website/scripts/live-blocks/src/helpers.js:193:15
    at async process (/Users/charlieegan3/Code/opa/docs/website/scripts/live-blocks/src/helpers.js:171:18)
    at async Promise.all (index 0)
```

I can see that this same issue is present in the production docs website:

https://www.openpolicyagent.org/docs/v0.36.1/policy-performance/#use-indexed-statements

vs latest (which is working)

https://www.openpolicyagent.org/docs/latest/policy-performance/#use-indexed-statements

There may be other versions that are broken but the error is so large it's hard determine exactly which versions are impacted.

**Comment by srenatus** [comment]
hm interesting, good catch!

I can't see those errors in the netlify logs, though: https://app.netlify.com/sites/openpolicyagent/deploys/63d02f5590b1b0000a78446f#L642

But obviously something's going on on the website, as you pointed out correctly. Weird!

**Comment by sspaink** [comment]
It looks like this might have been fixed already? When I visit https://www.openpolicyagent.org/docs/v0.36.1/policy-performance/#use-indexed-statements I don't see any errors. @charlieegan3 mind confirming this for me?

**Comment by charlieegan3** [comment]
I think we can close this yes. Live blocks are still not 100% reliable, and depend on a now outdated node version too. However, I don't think we're going to fix this rn.
