### ISSUE TITLE
server: "Txn is too big to fit into one request" followed by panic when trying out disk storage

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#5721]
I'm late to the game of disk storage, so I figured I'd try and catch up. The first attempt did not go well though, and I'm not sure what I did wrong.

**conf.yaml**
```
storage:
  disk:
    directory: "/tmp/storage"
    auto_create: true
    partitions:
      - "/users"

bundles:
  cli1:
    resource: "/load/bundle-opa-400.tar.gz"
    service: "cli1"

services:
  cli1:
    url: "https://dl.styra.com"
```

```
$ opa run -c conf.yaml
{"addrs":[":8181"],"diagnostic-addrs":[],"level":"info","msg":"Initializing server.","time":"2023-03-03T10:10:09+01:00"}
{"level":"error","msg":"Bundle activation failed: Txn is too big to fit into one request","name":"cli1","plugin":"bundle","time":"2023-03-03T10:10:30+01:00"}
{"level":"error","msg":"Bundle activation failed: Txn is too big to fit into one request","name":"cli1","plugin":"bundle","time":"2023-03-03T10:10:46+01:00"}
{"level":"error","msg":"Bundle activation failed: Txn is too big to fit into one request","name":"cli1","plugin":"bundle","time":"2023-03-03T10:11:02+01:00"}
{"level":"error","msg":"Bundle activation failed: Txn is too big to fit into one request","name":"cli1","plugin":"bundle","time":"2023-03-03T10:11:18+01:00"}
{"level":"error","msg":"Bundle activation failed: Txn is too big to fit into one request","name":"cli1","plugin":"bundle","time":"2023-03-03T10:11:34+01:00"}
{"level":"error","msg":"Bundle activation failed: Txn is too big to fit into one request","name":"cli1","plugin":"bundle","time":"2023-03-03T10:11:50+01:00"}
{"level":"error","msg":"Bundle activation failed: Txn is too big to fit into one request","name":"cli1","plugin":"bundle","time":"2023-03-03T10:12:06+01:00"}
{"level":"error","msg":"Bundle activation failed: Txn is too big to fit into one request","name":"cli1","plugin":"bundle","time":"2023-03-03T10:12:21+01:00"}
{"level":"error","msg":"Bundle activation failed: Txn is too big to fit into one request","name":"cli1","plugin":"bundle","time":"2023-03-03T10:12:38+01:00"}
{"level":"error","msg":"Bundle activation failed: Txn is too big to fit into one request","name":"cli1","plugin":"bundle","time":"2023-03-03T10:12:53+01:00"}
{"level":"info","msg":"Starting bundle loader.","name":"cli1","plugin":"bundle","time":"2023-03-03T10:12:53+01:00"}
panic: storage_invalid_txn_error: stale transaction

goroutine 113 [running]:
github.com/open-policy-agent/opa/storage/disk.(*Store).Abort(0x140006a6600, {0x14111ea6200?, 0x4eba2ae56292f8f3?}, {0x1057dfec8?, 0x14111ea6200?})
	/Users/anderseknert/git/opa/opa/storage/disk/disk.go:514 +0x2b4
github.com/open-policy-agent/opa/storage.Txn({0x1057ea250, 0x1400067e190}, {0x1057f09d0, 0x140006a6600}, {{0x0, 0x0, 0x0}, 0x0, 0x1, 0x1400031e928}, ...)
	/Users/anderseknert/git/opa/opa/storage/storage.go:96 +0xfc
github.com/open-policy-agent/opa/plugins/bundle.(*Plugin).activate(0x140001e4840, {0x1057ea250, 0x1400067e190}, {0x14007206cfc, 0x4}, 0x1402d95d560)
	/Users/anderseknert/git/opa/opa/plugins/bundle/plugin.go:569 +0x260
github.com/open-policy-agent/opa/plugins/bundle.(*Plugin).process(0x140001e4840, {0x1057ea250, 0x1400067e190}, {0x14007206cfc, 0x4}, {{0x1416edb0330, 0x24}, 0x1402d95d560, {0x0, 0x0}, ...})
	/Users/anderseknert/git/opa/opa/plugins/bundle/plugin.go:497 +0x49c
github.com/open-policy-agent/opa/plugins/bundle.(*Plugin).oneShot(0x140001e4840, {0x1057ea250?, 0x1400067e190?}, {0x14007206cfc, 0x4}, {{0x1416edb0330, 0x24}, 0x1402d95d560, {0x0, 0x0}, ...})
	/Users/anderseknert/git/opa/opa/plugins/bundle/plugin.go:448 +0x13c
github.com/open-policy-agent/opa/plugins/bundle.(*Plugin).newDownloader.func1({0x1057ea250?, 0x1400067e190?}, {{0x1416edb0330, 0x24}, 0x1402d95d560, {0x0, 0x0}, {0x1057eed60, 0x1417428c020}, {0x1057df168, ...}, ...})
	/Users/anderseknert/git/opa/opa/plugins/bundle/plugin.go:423 +0x94
github.com/open-policy-agent/opa/download.(*Downloader).oneShot(0x1417fb701a0, {0x1057ea250, 0x1400067e190})
	/Users/anderseknert/git/opa/opa/download/download.go:271 +0x20c
github.com/open-policy-agent/opa/download.(*Downloader).loop(0x1417fb701a0, {0x1057ea250, 0x1400067e190})
	/Users/anderseknert/git/opa/opa/download/download.go:219 +0x90
created by github.com/open-policy-agent/opa/download.(*Downloader).doStart
	/Users/anderseknert/git/opa/opa/download/download.go:183 +0xc8
```

It's a big bundle for sure, but that's what I'd expect to want disk storage for. 
I have read the docs on disk storage, but I can't see any option that possibly would help with this. To summarize:

* I'm not sure what I've done wrong (if I did something wrong?)
* The logs don't tell me
* The docs don't tell me
* panic

**Comment by srenatus** [comment]
I think it's related to your partitions. Try `/users/*`. And debug logging. (Sorry for the brevity I can fill in more later)

**Comment by anderseknert** [comment]
Thanks! At least that gives me a new error :)
```
error: initialize disk store: storage_internal_error: partitions are backwards incompatible (old: [/system/* /users], new: [/system/* /users/*], missing: [/users])
```

**Comment by anderseknert** [comment]
I tried adding both /users and /users/*, but that did not help. If we can improve these error messages in the process, that'd be good.

**Comment by anderseknert** [comment]
After clearing out my tmp-directory and changing to `/users/*`, I no longer get the "Txn is too big" errors. The bad news is that I now go straight to the panic:

```
opa run -c sconf.yaml -s https://dl.styra.com/load/bundle-opa-400.tar.gz
{"addrs":[":8181"],"diagnostic-addrs":[],"level":"info","msg":"Initializing server.","time":"2023-03-03T12:22:08+01:00"}
{"level":"info","msg":"Starting bundle loader.","name":"cli1","plugin":"bundle","time":"2023-03-03T12:22:08+01:00"}
panic: storage_invalid_txn_error: stale transaction

goroutine 81 [running]:
github.com/open-policy-agent/opa/storage/disk.(*Store).Abort(0x14000480c00, {0x140007e6900?, 0x8168e19299260868?}, {0x103a07ec8?, 0x140007e6900?})
	/Users/anderseknert/git/opa/opa/storage/disk/disk.go:514 +0x2b4
github.com/open-policy-agent/opa/storage.Txn({0x103a12250, 0x140006a2000}, {0x103a189d0, 0x14000480c00}, {{0x0, 0x0, 0x0}, 0x0, 0x1, 0x1400011e4e8}, ...)
	/Users/anderseknert/git/opa/opa/storage/storage.go:96 +0xfc
github.com/open-policy-agent/opa/plugins/bundle.(*Plugin).activate(0x140001f0780, {0x103a12250, 0x140006a2000}, {0x140000e3c4c, 0x4}, 0x140006c2000)
	/Users/anderseknert/git/opa/opa/plugins/bundle/plugin.go:569 +0x260
github.com/open-policy-agent/opa/plugins/bundle.(*Plugin).process(0x140001f0780, {0x103a12250, 0x140006a2000}, {0x140000e3c4c, 0x4}, {{0x14000204300, 0x24}, 0x140006c2000, {0x0, 0x0}, ...})
	/Users/anderseknert/git/opa/opa/plugins/bundle/plugin.go:497 +0x49c
github.com/open-policy-agent/opa/plugins/bundle.(*Plugin).oneShot(0x140001f0780, {0x103a12250?, 0x140006a2000?}, {0x140000e3c4c, 0x4}, {{0x14000204300, 0x24}, 0x140006c2000, {0x0, 0x0}, ...})
	/Users/anderseknert/git/opa/opa/plugins/bundle/plugin.go:448 +0x13c
github.com/open-policy-agent/opa/plugins/bundle.(*Plugin).newDownloader.func1({0x103a12250?, 0x140006a2000?}, {{0x14000204300, 0x24}, 0x140006c2000, {0x0, 0x0}, {0x103a16d60, 0x140006a4020}, {0x103a07168, ...}, ...})
	/Users/anderseknert/git/opa/opa/plugins/bundle/plugin.go:423 +0x94
github.com/open-policy-agent/opa/download.(*Downloader).oneShot(0x14000640ea0, {0x103a12250, 0x140006a2000})
	/Users/anderseknert/git/opa/opa/download/download.go:271 +0x20c
github.com/open-policy-agent/opa/download.(*Downloader).loop(0x14000640ea0, {0x103a12250, 0x140006a2000})
	/Users/anderseknert/git/opa/opa/download/download.go:219 +0x90
created by github.com/open-policy-agent/opa/download.(*Downloader).doStart
	/Users/anderseknert/git/opa/opa/download/download.go:183 +0xc8
```

**Comment by srenatus** [comment]
Can you try loading it from disk?

**Comment by anderseknert** [comment]
```
$ opa run -c sconf.yaml -s bundle-opa-400.tar.gz
error: initialization error: storage error: storage_invalid_patch_error: value cannot be partitioned
```
I tried changing `/users/*` to `/roles/*` thinking it might want me to match the data? But it did not seem to make a difference. The data is structured like:

```
{"roles":{"role0":[{"action":"action869707" ...
```

**Comment by srenatus** [comment]
you can have multiple partitions, I believe you might have a chance with both `/users/*` and `/roles/*` 🤔

**Comment by anderseknert** [comment]
That did not make a difference :/ I checked and according to `jq` there are only two top-level attributes in the bundle — `users` and `roles`.

```
cat ~/Desktop/bundle-opa-400/data.json | jq '. |= keys'
[
  "roles",
  "users"
]
```

**Comment by anderseknert** [comment]
Trying `/roles` and `/users` without the wildcard doesn't work either:
```
$ opa run -c sconf.yaml -s bundle-opa-400.tar.gz
error: initialization error: storage error: Txn is too big to fit into one request
```

I finally tried removing `partitions` entirely, and lo and behold! OPA actually started 🎉

```
$ curl localhost:8181/v1/data/roles/role0
{"result":[{"action":"action869707","resource":"resource279303"},{"action":"action183523","resource":"resource258803"},{"action":"action913284","resource":"resource551569"},{"action":"action914092","resource":"resource383681"},{"action":"action870790","resource":"resource595955"},{"action":"action404743","resource":"resource532561"},{"action":"action216789","resource":"resource210333"},{"action":"action578447","resource":"resource696725"},{"action":"action516735","resource":"resource872108"},{"action":"action227117","resource":"resource519703"}]}
```
Even a simple map lookup is now however a ~3 second operation 😅 And it doesn't seem to get any faster on repeated invocations.
```
{"client_addr":"127.0.0.1:62784","level":"info","msg":"Sent response.","req_id":7,"req_method":"GET","req_path":"/v1/data/roles/role0","resp_bytes":553,"resp_duration":2799.071334,"resp_status":200,"time":"2023-03-03T13:25:58+01:00"}
```

**Comment by srenatus** [comment]
Partitions are vital for performance and unpartitioned is never the right setting, I'm afraid. Have you tried both with wildcards?

**Comment by anderseknert** [comment]
Yes, https://github.com/open-policy-agent/opa/issues/5721#issuecomment-1453441223

**conf.yaml**
```
storage:
  disk:
    directory: "/tmp/storage"
    auto_create: true
    partitions:
      - "/roles/*"
      - "/users/*"
```

```
$ opa run --log-level debug -c conf.yaml -s bundle-opa-400.tar.gz
{"level":"info","msg":"badger: All 0 tables opened in 0s\n","time":"2023-03-03T13:40:04+01:00"}
{"level":"info","msg":"badger: Discard stats nextEmptySlot: 0\n","time":"2023-03-03T13:40:04+01:00"}
{"level":"info","msg":"badger: Set nextTxnTs to 0","time":"2023-03-03T13:40:04+01:00"}
{"level":"debug","msg":"badger: writeRequests called. Writing to value log","time":"2023-03-03T13:40:04+01:00"}
{"level":"debug","msg":"badger: Sending updates to subscribers","time":"2023-03-03T13:40:04+01:00"}
{"level":"debug","msg":"badger: Writing to memtable","time":"2023-03-03T13:40:04+01:00"}
{"level":"debug","msg":"badger: 2 entries written","time":"2023-03-03T13:40:04+01:00"}
{"level":"debug","msg":"partition pattern /roles/*: key count: 0 (estimated size 0 bytes)","time":"2023-03-03T13:40:04+01:00"}
{"level":"debug","msg":"partition pattern /users/*: key count: 0 (estimated size 0 bytes)","time":"2023-03-03T13:40:04+01:00"}
{"level":"debug","msg":"partition pattern /system/*: key count: 0 (estimated size 0 bytes)","time":"2023-03-03T13:40:04+01:00"}
error: initialization error: storage error: storage_invalid_patch_error: value cannot be partitioned
```

**Comment by srenatus** [comment]
Hm interesting. Giving your test data, I thought those partitions should work 🤔 Ah, right. users/user0 is an array, and so is roles/role0, and that won't work with those partitions...? looks like it? I'd add some debug printfs [around the error return](https://github.com/open-policy-agent/opa/blob/5c183f5ecb68e31d941f0f156b01c78c93e86387/storage/disk/txn.go#L344) to figure out what's wrong

**Comment by srenatus** [comment]
Have you tried a smaller bundle size? Just to see if the loading into the disk store works with the other partitions (/users, /rules)?

**Comment by anderseknert** [comment]
Yep, that seems to be it — the arrays present in the data seem to be the cause, as JSON unmarshalling into a map unsurprisingly fails.

![Screenshot 2023-03-03 at 13 49 14](https://user-images.githubusercontent.com/510711/222724880-2ced4191-cc40-4f40-bfaa-f2e0e0b34f25.png)

This seems to be "documented" in the form of a comment:

https://github.com/open-policy-agent/opa/blob/5c183f5ecb68e31d941f0f156b01c78c93e86387/storage/disk/txn.go#L322-L323

It isn't entirely clear to me though whether arrays can't be in the data _at all_, or just not as a "top level" value. The example partitioning scheme from the docs even has a case where arrays seem to be stored as values, but could be I'm not reading that correctly.

![Screenshot 2023-03-03 at 13 58 10](https://user-images.githubusercontent.com/510711/222726186-23f3a9a0-542c-46f4-aad7-bdea8ff677ba.png)

**Comment by srenatus** [comment]
Maybe my advise was wrong because I'm misremembering things. From the docs, I'd think it would work, indeed. But also, from the docs, it seems like /users and /roles would be the proper partitions to use here. I'm not sure if there's a significant difference in the code flow between (3) and your example -- if the array values only work with pattern partitions...? That would be odd, though.

Also, I don't understand how the txn is too big if it's split, but not too big if it isn't -- that might be something internal to badger, though, that I'm unaware of.

**Comment by anderseknert** [comment]
Yeah. Just for testing, I created a bundle with a single user and role, and now the `/users` and `/roles` partitioning scheme works as expected. That's good, but large bundles are of course pretty much the _raison d'etre_ for disk storage 😅

**Comment by ashutosh-narkar** [comment]
Looks like all your data is in one file. Is that correct? Badger has a limitation on the size of each transaction and that depends on the size of the table. If you split your data in multiple files and make it part of a large bundle, OPA will internally create multiple transactions to write that data to the underlying store.

**Comment by anderseknert** [comment]
@ashutosh-narkar `opa build` will merge all data into one big `data.json` file as part of the build process, so in order to do what you suggest, the user have to manually build a tarball, which even if it works doesn't seem like something that should be required in order to use disk storage, or what do you think?

**Comment by ashutosh-narkar** [comment]
This is a limitation right now for the large bundle use case when all data is in a single file. I can think of couple of options here either OPA automatically figures out how to break down the file into chunks that respect the max transaction size (maybe use the partitions/keys) and/or we update `opa build` with a mode to not merge all the data. For the later it's still possible one file can exceed the transaction limit, so OPA will have to manage this internally somehow I think.

**Comment by anderseknert** [comment]
I think the former would be the best course of action, as whoever builds the bundle might not be the same as whoever runs it later.

**Comment by salbracco24** [comment]
This issue is still relevant. Recently, I was trying to run OPA with our data (2.4 MB) and policy bundle (0.979 MB). I was able to run OPA just fine with these bundles without disk storage (Badger) enabled (although RAM usage was around 2.22 GB), but when I enabled Badger, it would fail with this error:
error: initialization error: storage_internal_error: Txn is too big to fit into one request
How can I solve this? I played around with different partitions, /resources/* /resources/*/* /resources/*/*/* and no partitions at all, and they all crashed OPA. I tried smaller data and policy bundles, and they worked fine, so maybe OPA has some weird bug?

**Comment by salbracco24** [comment]
That's so silly, Stale bot. I really hope this is resolved.

**Comment by anderseknert** [comment]
Nevermind the bot, that's just what it does :) In case you missed the [EOPA](https://github.com/open-policy-agent/eopa) announcement, that might be another option to look into. Its storage engine is something else entirely, and memory consumed is often something like 0.1x compared to OPA.

**Comment by salbracco24** [comment]
@anderseknert is EOPA a drop-in replacement for OPA? How difficult would it be to upgrade from OPA to EOPA? Does it still work with data and policy bundles?

**Comment by anderseknert** [comment]
Yes, it is a drop-in replacement, and can be used with all the same commands and args. You'll want to check out the docs for EOPA to learn about how to enable some features specific to that engine, like how to build compressed data bundles, etc.

**Comment by salbracco24** [comment]
Thanks for the recommendation, @anderseknert we'll look into it, if needed. I think for now, we are looking to resolve this issue by making the individual files within the data bundle smaller.
